# Generated by Django 5.1.5 on 2025-02-18 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email_pessoal', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('processador', models.CharField(blank=True, max_length=100, null=True)),
                ('memoria', models.CharField(blank=True, max_length=100, null=True)),
                ('disco_rigido', models.CharField(blank=True, max_length=100, null=True)),
                ('sistema_operacional', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_mac', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_mac_wifi', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_exclusao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='gestao_ti.colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='gestao_ti.filial'),
        ),
        migrations.CreateModel(
            name='HistoricoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_ti.colaborador')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='gestao_ti.email')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionando', models.BooleanField(default=True)),
                ('defeito', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to='gestao_ti.colaborador')),
                ('equipamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario', to='gestao_ti.equipamento')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='gestao_ti.filial')),
                ('maquina', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario', to='gestao_ti.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('tipo_vencimento', models.CharField(blank=True, choices=[('anual', 'Anual'), ('mensal', 'Mensal'), ('pontual', 'Pontual')], max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sistemas', to='gestao_ti.filial')),
            ],
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credenciais', to='gestao_ti.sistema')),
            ],
        ),
    ]
