# Generated by Django 5.1.5 on 2025-02-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ti', '0003_rename_email_colaborador_email_pessoal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sistema',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
