# Generated by Django 5.1.5 on 2025-02-04 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_ti', '0004_colaborador_ativo_filial_ativo_sistema_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='cnpj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sistema',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sistemas', to='gestao_ti.filial'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='tipo_vencimento',
            field=models.CharField(blank=True, choices=[('anual', 'Anual'), ('mensal', 'Mensal'), ('pontual', 'Pontual')], max_length=50, null=True),
        ),
    ]
